EMOTION_LABELS = [
    "anger",
    "sweet",
    "fear",
    "sad",
    "nice",
    "emotional",
    "love",
    "drama",
    "depressed",
    "worried",
    "tensed",
    "stressed",
    "sick",
    "fight",
    "calm",
    "polite",
    "joy",
    "frustrated",
    "hopeful",
    "confused",
    "grateful",
]

POSITIVE_EMOTIONS = {"love", "nice", "sweet", "calm", "polite", "joy", "hopeful", "grateful"}
ALERT_EMOTIONS = {
    "anger",
    "fear",
    "depressed",
    "worried",
    "tensed",
    "stressed",
    "fight",
    "sick",
    "sad",
    "frustrated",
}

EMOTION_HINTS = {
    "anger": "Conflict or frustration is high; use de-escalation language.",
    "sweet": "Tone is warm and affectionate; keep language personal and positive.",
    "fear": "Anxiety indicators are present; add reassurance and risk clarity.",
    "sad": "Low mood signals detected; use empathetic and supportive messaging.",
    "nice": "Friendly tone present; maintain respectful conversational style.",
    "emotional": "High emotional intensity; avoid abrupt or overly dry responses.",
    "love": "Strong affection cues; highlight trust and appreciation.",
    "drama": "Narrative conflict/volatility is notable; provide balanced framing.",
    "depressed": "Depressive signals found; recommend supportive and human-first outreach.",
    "worried": "Concern is elevated; include clear next steps and certainty where possible.",
    "tensed": "Tension level is high; simplify communication and reduce pressure.",
    "stressed": "Stress markers detected; suggest prioritization and practical relief actions.",
    "sick": "Health discomfort indicators present; avoid harsh wording and provide care-oriented tone.",
    "fight": "Aggressive/conflict language found; recommend neutral and non-confrontational replies.",
    "calm": "Composed tone; continue clear and stable messaging.",
    "polite": "Respectful style present; keep formal and courteous response style.",
    "joy": "Positive excitement detected; reinforce achievements and momentum.",
    "frustrated": "Obstruction/pain points are evident; prioritize resolution steps.",
    "hopeful": "Optimistic intent present; align with clear forward plans.",
    "confused": "Ambiguity markers found; provide concise clarification and examples.",
    "grateful": "Appreciation cues present; acknowledge and reinforce positive relationship.",
}

# Hybrid signal words to improve model robustness in real-world short inputs.
KEYWORD_LEXICON = {
    "anger": ["angry", "furious", "rage", "mad", "annoyed", "outraged"],
    "sweet": ["sweet", "gentle", "adorable", "tender", "kindhearted"],
    "fear": ["afraid", "fear", "scared", "unsafe", "panic", "threat"],
    "sad": ["sad", "heartbroken", "cry", "down", "unhappy", "sorrow"],
    "nice": ["nice", "pleasant", "friendly", "helpful", "good"],
    "emotional": ["emotional", "overwhelmed", "tears", "intense", "deeply moved"],
    "love": ["love", "adore", "affection", "cherish", "romantic"],
    "drama": ["drama", "dramatic", "scene", "overreaction", "chaotic"],
    "depressed": ["depressed", "hopeless", "empty", "numb", "worthless"],
    "worried": ["worried", "concerned", "anxious", "uncertain", "uneasy"],
    "tensed": ["tense", "tensed", "stiff", "strained", "pressured"],
    "stressed": ["stressed", "burnout", "pressure", "overloaded", "exhausted"],
    "sick": ["sick", "ill", "fever", "pain", "nausea", "unwell"],
    "fight": ["fight", "attack", "clash", "argue", "conflict", "war"],
    "calm": ["calm", "steady", "peaceful", "composed", "settled"],
    "polite": ["polite", "courteous", "respectful", "please", "thank you"],
    "joy": ["joy", "happy", "delighted", "excited", "thrilled"],
    "frustrated": ["frustrated", "blocked", "stuck", "irritated", "fed up"],
    "hopeful": ["hopeful", "optimistic", "promising", "expecting", "encouraged"],
    "confused": ["confused", "unclear", "mixed", "lost", "puzzled"],
    "grateful": ["grateful", "thankful", "appreciate", "blessed", "indebted"],
}
